version: '3.9'

services:
  combination-flooding:
    image: ${APP_NAME:-combination-flooding}:${APP_VERSION:-1.0.1}
    container_name: ${APP_NAME:-combination-flooding}
    restart: always
    user: root
    env_file:
      - ./runtime.env
    ports:
      - "${EXPOSED_PORT:-35000}:${CONTAINER_PORT:-80}"
