apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-test.fullname" . }}
  labels:
{{ include "k3s-test.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
{{ include "k3s-test.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if eq (.Values.service.type | default "NodePort") "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
{{- end }}
